filter:
    excluded_paths:
        - 'vendor/*'
tools:
    php_code_sniffer:
        enabled: true
        command: phpcs
        extensions:
            - php
        filter:
            paths: ["src/*", "tests/*"]
        config:
            standard: PSR2

    php_cpd:
        enabled: true
        command: phpcpd
        min_lines: 5
        min_tokens: 70
        names:
            - '*.php'
        excluded_dirs: ["vendor", "tests"]

    php_pdepend:
        enabled: true
        command: pdepend
        excluded_dirs:
            - vendor
            - tests
        configuration_file: null
        suffixes:
            - php